body:
  - type: input
    attributes:
      name: firefox_fp
      label: Firefox Folder Location
      description: The folder that contains the firefox executable to be used when opening websites. When given, FKB will open the bookmark in the profile it comes from using the exe from this folder. Leave blank to let Flow Launcher pick where to open it.
  - type: textarea
    attributes:
      name: profile_path_data
      label: Profile Data Path
      description: Go to `about:profiles` in firefox, and put the `root path` value for each profile you want to get the bookmarks on, on its own line.